name: Docker Compose Test

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - php: '8.4'
            laravel: 12
          - php: '8.5'
            laravel: 12

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          path: 'pier'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, fileinfo
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Create a new laravel application
        run: composer create-project laravel/laravel app "${{ matrix.laravel }}.x" --remove-vcs --no-interaction --prefer-dist

      - name: Link Pier Repository
        run: |
          composer config minimum-stability dev
          composer config repositories.pier path ../pier
          composer require social-sync/pier:* --dev -W
        working-directory: app

      - name: Install Pier into App
        run: |
          php artisan pier:install --php=${{ matrix.php }} --no-interaction
          php artisan pier:publish --no-interaction
        working-directory: app

      - name: Remove Pier
        run: composer remove social-sync/pier --dev --no-interaction -W
        working-directory: app

      - name: Start Pier Container
        run: ../pier/bin/pier up -d --wait
        working-directory: app

      - name: Run Migrations
        run: ../pier/bin/pier artisan migrate --no-interaction
        working-directory: app

      - name: Run Tests in Pier Container
        run: ../pier/bin/pier test
        working-directory: app

      - name: Stop Pier Container
        run: ../pier/bin/pier down
        working-directory: app
